version: '3'

services:
  aws:
    build: .
    platform: linux/amd64
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials
      - ~/.aws/config:/root/.aws/config
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
